### ISSUE TITLE
Create 16F7A glyph variant for hmd and hmz

### ISSUE THREAD

**Issue by kienwt** [silnrsi/MiaoUnicode#12]
The legacy font used by the Big Flowery Miao (hmd) and Hmong Sa (hmz) teams have an angled version of vowel ei, 16F7A.  Should create a variant for BFM and Hmong Sa that matches the legacy font as in the image below.

![vowel_ei](https://cloud.githubusercontent.com/assets/18396131/19599055/0550be0e-97d1-11e6-8666-7c379b6963fb.JPG)

The current version in MiaoUnicode is suitable for Lipo.  Suggest making the current glyph the Lipo variant and the new glyph the default.

**Comment by kienwt** [comment]
After email discussion, recommendation is to make the new angled glyph the hmd and hmz variant, leaving default curved glyph unchanged.  The original Pollard shape was curved and is used by more teams.

**Comment by jvgaultney** [comment]
New glyph added - miao_ei.hmd - that is the angled variant

**Comment by jvgaultney** [comment]
Now also added another angled variant - miao_ei.ycmphmd - although that glyph suffix may best be changed at some point

**Comment by kienwt** [comment]
The team likes it.
