### ISSUE TITLE
Adjust size and position for vowel 16F64 in Above position

### ISSUE THREAD

**Issue by kienwt** [silnrsi/MiaoUnicode#34]
The team requests the following changes for vowel 16F64 in the Above position:
1) Use normal sized glyph, not ycmp version.
2) Move to right and lower as in attached image.

![img_20160811_200341 1](https://user-images.githubusercontent.com/18396131/32641239-ca29c418-c607-11e7-8970-16159dcca351.jpg)

They said it's only used with 16F10, 16F2E, and 16F33.

**Comment by kienwt** [comment]
Before:
![before](https://user-images.githubusercontent.com/18396131/33719375-73b1a32c-db9b-11e7-936b-e3462ef1d293.PNG)


After:
![after](https://user-images.githubusercontent.com/18396131/33719384-7944a1cc-db9b-11e7-97ec-e569b619d82b.PNG)

**Comment by mhosken** [comment]
Happy to simplify for this. But every issue causes questions.
1. Is this the position for all vowels with this tone?
2. Is this position to get the right hand side of the vowels to hang over?
3. Does this language have foot vowels too and if so, are they similarly
aligned?
4. If other vowels don't hang right, what happens with this vowels in a
vowels sequence? (Presumes they have vowel sequences)
5. Which language is requesting this?

Guess what. Oh for an orthography statement. 😀

GB,
Martin

**Comment by kienwt** [comment]
This is for hmd and they requested this position only for this vowel.  When they used the legacy font, they combined two vowels in different positions to form this one.
