### ISSUE TITLE
Raise trigraphs to head position

### ISSUE THREAD

**Issue by cheuk879** [silnrsi/MiaoUnicode#8]
Currently only singletons & digraphs are rendered properly in head position, but at least 1 language is known to have trigraphs, & these are currently rendered on the base line even when followed by 16F91.  The trigraph should be raised to head position.

**Comment by kienwt** [comment]
![trigraph](https://cloud.githubusercontent.com/assets/18396131/20422000/85692310-ada2-11e6-9461-1888f017798b.JPG)
